<?php

$arrMarcas = [
    1 => "Audi",
    2 => "BMW",
    3 => "Chevrolet",
    4 => "Citroen",
    5 => "Fiat",
    6 => "Ford",
    7 => "Hyundai",
    8 => "Honda",
    9 => "JAC",
    10 => "Jaguar",
    11 => "Jeep",
    12 => "Kia",
    13 => "Land Rover",
    14 => "Lexus",
    15 => "Mercedes",
    16 => "Mitsubishi",
    17 => "Nissan",
    18 => "Peugeot",
    19 => "Porsche",
    20 => "RAM",
    21 => "Subaru",
    22 => "Suzuki",
    23 => "Toyota",
    23 => "Volkswagen",
    23 => "Volvo",
];
